version: "3.8"

services:
  cart:
    container_name: cart
    build: 
      context: .
      dockerfile: ./cart/Dockerfile
      
    ports:
      - "8082:8082"
    environment:
      - BASE_URL=http://route256.pavl.uk:8080
      - TOKEN=testtoken
      - PORT=0.0.0.0:8082
      - MAX_RETRIES=3
      - INITIAL_BACKOFF=500ms
      - LOMS_ADDR=loms:50051
    networks:
      - backend
    depends_on:
      - loms
  
  loms:
    container_name: loms
    build: 
      context: .
      dockerfile: ./loms/Dockerfile
    ports:
      - "50051:50051" # grpc
      - "8088:8088" # grpc gateway
    environment:
      - LOMS_GRPC_PORT=0.0.0.0:50051
      - LOMS_HTTP_PORT=0.0.0.0:8088
      - LOMS_STOCK_FILE=/loms/stock-data.json
      - LOMS_SWAGGER_FILE=/loms/loms.swagger.json
    networks:
      - backend

networks:
  backend:
    driver: bridge

