version: "3.8"

services:
  cart:
    container_name: cart
    build: ./cart/
    ports:
      - "8082:8082"
    environment:
      - BASE_URL=http://route256.pavl.uk:8080
      - TOKEN=testtoken
      - PORT=8082
      - MAX_RETRIES=3
      - INITIAL_BACKOFF=500ms
